spring.application.name=gateway-svc
server.port=8080

# because we haven't created the discovery service yet, and we still added eureka client dependency
spring.cloud.discovery.enabled=false

# because we haven't created the config service yet, and we still added config dependency
spring.cloud.config.enabled=false

# expose all actuator endpoints by default only health is exposed
management.endpoints.web.exposure.include=*
