spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: keynote-svc
              uri: http://localhost:8081
              predicates:
                - Path= /api/keynotes/**
            - id: conference-svc
              uri: http://localhost:8082
              predicates:
                - Path= /api/conferences/**